// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type DailyTransactionReport struct {
	ID                     int64     `json:"id"`
	NumTransactions        int32     `json:"num_transactions"`
	AvgTransactionAmount   float64   `json:"avg_transaction_amount"`
	TotalTransactionAmount int32     `json:"total_transaction_amount"`
	TotalCommission        float64   `json:"total_commission"`
	Day                    string    `json:"day"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
}

type Transaction struct {
	ID                int64          `json:"id"`
	TransactionID     string         `json:"transaction_id"`
	FromAccountID     string         `json:"from_account_id"`
	ToAccountID       string         `json:"to_account_id"`
	TransactionAmount float64        `json:"transaction_amount"`
	Commission        float64        `json:"commission"`
	Description       sql.NullString `json:"description"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}
