// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	GetTransaction(ctx context.Context, id int64) (Transaction, error)
	ListTransactions(ctx context.Context) ([]Transaction, error)
}

var _ Querier = (*Queries)(nil)
