// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: transaction.sql

package db

import (
	"context"
	"database/sql"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (transaction_id, from_account_id, to_account_id, transaction_amount, description)
VALUES ($1, $2, $3, $4, $5) RETURNING id, transaction_id, from_account_id, to_account_id, transaction_amount, description, created_at, updated_at
`

type CreateTransactionParams struct {
	TransactionID     string         `json:"transaction_id"`
	FromAccountID     string         `json:"from_account_id"`
	ToAccountID       string         `json:"to_account_id"`
	TransactionAmount int32          `json:"transaction_amount"`
	Description       sql.NullString `json:"description"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.TransactionID,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.TransactionAmount,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.TransactionAmount,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, transaction_id, from_account_id, to_account_id, transaction_amount, description, created_at, updated_at
FROM transactions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.TransactionAmount,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, transaction_id, from_account_id, to_account_id, transaction_amount, description, created_at, updated_at
FROM transactions
ORDER BY id LIMIT $1
OFFSET $2
`

type ListTransactionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.TransactionAmount,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
