version: '3'

services:
  gateway:
    build:
      context: ./../gateway
      dockerfile: ./../gateway/gateway.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  # Database container for accounts
  account_db_postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accounts
    volumes:
      - ./db-data/account-postgres/:/var/lib/postgresql/data

  account-service:
    build:
      context: ./../account-service
      dockerfile: ./../account-service/account-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - account_db_postgres