version: '3'

services:
  gateway:
    build:
      context: ./../gateway
      dockerfile: ./../gateway/gateway.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1